Details pop up window- a popup window for projects
Fsher07/Fsher07.github.io pull request #6
Opened 2022-03-03 08:42 UTC by Fsher07

Created a popup window that includes details of project. Reachable when click on see projects. Stored object in an array. Created elements dynamically via JavaScript function.

2022-03-03 10:08 UTC, brytebee requested changes
Hi, @Fsher07 👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Status: Invalid Code Review Request

![](https://media.giphy.com/media/OQeKGexhYKVjLaSzPd/giphy.gif)

_**You have submitted a project with incomplete linter files. Kindly check [this](https://github.com/microverseinc/linters-config/tree/master/html-css-js) and add appropriate files.**_

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-03-03 14:27 UTC, Fsher07 commented on index.html
>  </head>
Thank you for your feedback. Now,I added Eslint file and fix errors.

2022-03-03 15:07 UTC, mike2611 requested changes
Hi @Fsher07 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-03 15:07 UTC, mike2611 commented on index.html
> -      <button type="button" class="projectbtn btn">See Project</button>
- [ ] Great work in the mobile version of your project your pop-up looks great, however, in your desktop version, your pop-up is out center. please fix this and make sure to follow the template in Figma 
![image](https://user-images.githubusercontent.com/28109626/156590945-169d450e-b468-4afa-ab48-f9f57d1eb4e1.png)

2022-03-03 15:19 UTC, Fsher07 commented on index.html
>        <h3 class="project-titles ProjectPage-h2">Data Dashboard<br> Healthcare</h3>
Excuse me, I didn't get the point. I created an array that stores objects of the pop-up windows and I used those objects to create a project window.  Or, should I remove the project sections elements from index.html and create them with javascript ?

2022-03-03 19:17 UTC, mike2611 commented on index.html
>        <h3 class="project-titles ProjectPage-h2">Data Dashboard<br> Healthcare</h3>
Hi @Fsher07, yes you should remove the hardcoded cards from your project section, and create your cards using the data of your object dynamically.

2022-03-03 19:24 UTC, mike2611 commented on index.html
>        <h3 class="project-titles ProjectPage-h2">Data Dashboard<br> Healthcare</h3>
You can do this by looping through your array of objects and creating a new element for each one of your objects inside your array, and then appending each element to your projects section.

2022-03-03 19:36 UTC, mike2611 commented on index.html
>        <h3 class="project-titles ProjectPage-h2">Data Dashboard<br> Healthcare</h3>
So for example, if you have only six objects in your array your projects section only needs to show six elements as this are created dynamically. 

![image](https://user-images.githubusercontent.com/28109626/156639404-e803899c-b3d6-45a4-9365-e86cca27a288.png)

2022-03-04 09:24 UTC, elyor-doniyorov approved these changes
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
- [OPTIONAL] To make it more informative, kindly provide a project `description`, `screenshot`, `how to set up the project` section in your Readme.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-04 11:01 UTC, merged